package se.gu.git.scenarios;

public enum ActionPrecondition {
    NONE,
    //folder specifc preconditions
    PARENT_ANNOTATED_AND_NO_ANNOTATED_SIBLINGS_EXIST,
    PARENT_ANNOTATED_AND_ANNOTATED_SIBLINGS_EXIST,
    PARENT_UNANNOTATED_AND_ANNOTATED_SIBLINGS_EXIST,
    PARENT_UNANNOTATED_AND_NO_ANNOTATED_SIBLINGS_EXIST,
    PARENT_UNANNOTATED_AND_NO_OTHER_SIBLINGS_EXIST,
    PARENT_NOT_EXISTS_AND_NO_OTHER_SIBLINGS_EXIST,
    //other file, fragment and line preconditions
    NO_ANNOTATED_SIBLINGS_EXIST,
    ANNOTATED_SIBLINGS_EXIST,
    NO_ANNOTATED_SIBLINGS_EXIST_AND_OTHER_SIBLINGS_EXIST,
    NO_ANNOTATED_SIBLINGS_EXIST_AND_NO_OTHER_SIBLINGS_EXIST,
    NO_ANNOTATED_SIBLINGS_EXIST_AND_NO_OTHER_SIBLINGS_EXIST_IN_ANCESTRY,
    //fragment specific
    NOT_ALL_LINES_IN_CLUSTER_ARE_ANNOTATED,
    NO_ANNOTATED_SIBLINGS_EXIST_AND_CLUSTERS_ARE_TWO_OR_MORE,
    NO_ANNOTATED_SIBLINGS_EXIST_AND_CLUSTERS_ARE__LESSTHAN_TWO_AND_PARENT_SIBLING_FRAGMENTS_EXIST,
    NO_ANNOTATED_SIBLINGS_EXIST_AND_CLUSTERS_ARE__LESSTHAN_TWO_AND_PARENT_SIBLING_FRAGMENTS_NOT_EXISTS
}
