package se.gu.git.scenarios;

public enum PredictionAction {
    DO_NOTHING,
    ASSUME_PARENT_FOLDER_MAPPING,
    PREDICT_WITH_ANNOTATED_SIBLINGS,
    PREDICT_WITH_ALL_SIBLINGS,
    PREDICT_WITH_PARENTS_SIBLINGS,
    ASSUME_FOLDER_MAPPING,
    PREDICT_WITH_CHILDREN_OF_PARENTS_SIBLINGS,
    USE_LINE_SCENARIOS,
    ASSUME_FILE_MAPPING,
    PREDICT_WITH_ALL_CLUSTERS,
    PREDICT_WITH_PARENTS_SIBLING_FRAGMENTS,
    PREDICT_WITH_PARENTS_SIBLING_CLUSTERS,
    ASSUME_FRAGMENT_MAPPING,
    RETRAIN_MODEL


}
